# Generated by Django 5.0.1 on 2024-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id_bidang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bidang', models.CharField(max_length=255)),
            ],
        ),
    ]
