# Generated by Django 5.0.1 on 2024-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=255)),
            ],
        ),
    ]
