# Generated by Django 5.0.1 on 2024-01-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id_knowledge', models.AutoField(primary_key=True, serialize=False)),
                ('judul_knowledge', models.CharField(max_length=255)),
                ('gambar_unggulan', models.ImageField(blank=True, null=True, upload_to='knowledge_images/')),
                ('tipe_knowledge', models.CharField(choices=[('jabatan', 'By Jabatan'), ('taxonomy', 'By Taxonomy')], max_length=20)),
                ('konten_knowledge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.bidang')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.jabatan')),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.taxonomy')),
            ],
        ),
    ]
