# Generated by Django 5.0.1 on 2024-01-16 21:52

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='konten_knowledge',
            field=django_quill.fields.QuillField(),
        ),
    ]
