# Generated by Django 5.0.1 on 2024-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_knowledge_konten_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='gambar_unggulan',
            field=models.ImageField(blank=True, null=True, upload_to='mystaticfiles/knowledge_images/'),
        ),
    ]
