# Generated by Django 5.0.1 on 2024-02-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_knowledge_gambar_unggulan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyPengetahuan',
            fields=[
                ('id_taxonomy_pengetahuan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_taxonomy_pengetahuan', models.CharField(max_length=255)),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.taxonomy')),
            ],
        ),
    ]
