# Generated by Django 5.0.1 on 2024-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpengguna',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
