# Generated by Django 5.0.1 on 2024-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userpengguna_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpengguna',
            name='bio',
            field=models.TextField(default='bio'),
            preserve_default=False,
        ),
    ]
